### ISSUE TITLE
MIT/GNU Scheme: Not compatible with 10.1.10

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#123]
```
-> (yunitest mini) => ERROR!
Unbound variable: nmv-header?
;... aborted
```

perhaps upstream http://git.savannah.gnu.org/cgit/mit-scheme.git/commit/?id=f821026072c161106999d3f05a3504b0acf53519 , switching back 10.1.9 meantime.

**Comment by lassik** [comment]
@arthurgleckler Could you persuade someone from MIT Scheme to look through the MIT issues in this repo? There are not many of them, and it would be a good benchmark for the level of R7RS compatibility in MIT Scheme.

**Comment by okuoku** [comment]
@lassik : I think this can be simply fixed using latest git HEAD; AFAIK `10.1.10` [has some other known-issues](https://lists.gnu.org/archive/html/mit-scheme-devel/2020-02/msg00003.html) which is already fixed in HEAD. 

Moreover, I will file issues once I could confirm implementation issues (these under [Extern-copied](https://github.com/okuoku/yuni/issues?q=label%3AExtern-Copied) label). As a compatibility layer, Yuni does *far* beyond standard Scheme program, that would be hard to track down issues without reducing case on my side.

**Comment by okuoku** [comment]
... but I'm struggling with compile git HEAD of `mit-scheme` on my environment. I'll try this later anyway.

**Comment by lassik** [comment]
That sounds good :) Thank you for your hard work on Scheme compatibility.

**Comment by lassik** [comment]
Do you use Docker? I just made a MIT Scheme container at [scheme-containers](https://github.com/scheme-containers/mit-scheme). It'll go up on Docker Hub once the build is done, https://hub.docker.com/u/schemers. We could add a HEAD container as well. I can add you to scheme-containers if you want to experiment. I've never built MIT Scheme directly from Git.

**Comment by arthurgleckler** [comment]
Chris Hanson, MIT Scheme's maintainer, has been working on R7RS compatibility in the past few months.  I'm hoping that the fruits of his work will be out once he has a chance to release version 11.

In the meantime, if you're struggling to build MIT Scheme from head, make sure to do:

  ./configure --enable-cross-compiling

Incompatible changes were introduced in the most recent version that require cross-compilation in order to build from HEAD.  (It's cross-compilation in the sense of an incompatible ABI, not an incompatible architecture.  MIT Scheme uses a new calling convention that gives a roughly four-times performance boost.  But an earlier version of MIT Scheme is required to bootstrap the most recent one.)

**Comment by okuoku** [comment]
Confirmed Yuni work as expected with 10.1.11.
